app:
    resource: "@AppBundle/Controller/"
    type:     annotation

oneup_uploader:
    resource: .
    type: uploader

consultants:
    type:     rest
    resource: AppBundle\Controller\ConsultantApiController
    prefix:   api/
    
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"