<?php

namespace AppBundle\Repositories;

use AppBundle\Entity\Favoris;

/**
 * FavorisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FavorisRepository extends \Doctrine\ORM\EntityRepository
{
    public function findUserFavorites($userId){
        $favorites= $this->findBy(array("userId"=>$userId, "isavailable"=>true));
        $result= array();
        foreach ($favorites as $fav){
            $result[]= $fav->getConsultantId();
        }
        return $result;
    }
    
    
    public function findUserFavoritesConsultants($userId){
        $consultants= $this->findUserFavorites($userId);
        return $this->_em->getRepository('AppBundle:Consultant')->findBy(array("id"=>$consultants));
    }
    
    public function addUserFavorite($userId, $consultantId){
        $existFav = $this->findOneBy(array("userId"=>$userId, "consultantId"=>$consultantId));
        if(!empty($existFav)){
            $existFav->setIsavailable(true);
            $existFav->setUpdated(new \DateTime("now"));
        }else{
            $fav= new Favoris();
            $fav->setUserId($userId);
            $fav->setConsultantId($consultantId);
            $fav->setIsavailable(true);
            $fav->setCreated(new \DateTime("now"));
            $fav->setUpdated(new \DateTime("now"));
            $this->_em->persist($fav);
        }
        $this->_em->flush();
        return true;
    }
    
    public function removeUserFavorite($userId, $consultantId){
        $existFav = $this->findOneBy(array("userId"=>$userId, "consultantId"=>$consultantId));
        if(!empty($existFav)){
            $existFav->setIsavailable(false);
            $existFav->setUpdated(new \DateTime("now"));
            $this->_em->flush();
            return true;
        }else{
            return false;
        }
    }
    
}
