<?php

namespace AppBundle\Repositories;

use AppBundle\Entity\Searches;
/**
 * SearchesReposi      $search->setName("");
tory
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SearchesRepository extends \Doctrine\ORM\EntityRepository
{
    
  public function insertSearch($userId, $searchQuery){
      $search= new Searches();
      $search->setUserId($userId);
      $search->setQuery($searchQuery);
      $search->setIsavailable(false);
      $search->setCreated(new \DateTime(""));
      $search->setUpdated(new \DateTime(""));
      $this->_em->persist($search);
      $this->_em->flush();
  }
  
  public function saveLastUserSearch($userId ){
      $search= $this->findOneBy(array("userId"=>$userId), array("created"=>"DESC"));
      $search->setIsavailable(true);
      $search->setUpdated(new \DateTime(""));
      $this->_em->flush();
      return $search->getId();
  }
  
  public function removeUserSearch($searchId){
      $search= $this->find($searchId);
      if(empty($search)){
          return false;
      }
      $search->setIsavailable(false);
      $search->setUpdated(new \DateTime(""));
      $this->_em->flush();
      return true;
  }
  
  
  public function findUserSearches($userId ){
        $searches= $this->findBy(array("userId"=>$userId,
                          "isavailable"=>true));
        foreach ($searches as $search){
            $this->changeSearchName($search);
        }
        return $searches;
  }
  
  private function changeSearchName($search){
      if(empty($search->getName())){
          parse_str($search->getQuery(), $query);
          $name= "";
          if(empty($query["inputKeywords"])){
              $name .= "No keywords";
          }else{
              $name .= $query["inputKeywords"];
          }
          if(!empty($query["exp-choice"])){
              $name .= " - ".$query["exp-choice"];
          }
          $name .= " - Availability ";
          if($query["rangeAvailability-a"]==0){
              $name.= "Asap";
          }else{
             $name.= $query["rangeAvailability-a"]. " weeks";
          }
          $name.= " to ".$query["rangeAvailability-b"]. " weeks";
          $search->setName($name);
      }
  }
}
